/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/
package  org.platkmframework.example.openapi.domain.vo;

import java.io.Serializable;

public class ProductoVO implements Serializable{

	private static final long serialVersionUID = 1L;

	private java.lang.Integer id;

	private java.lang.String nombre;

	private java.lang.Long precio;

	private java.lang.Integer stock;


  public  java.lang.Integer getId(){
    return this.id;
  }

  public  ProductoVO setId (java.lang.Integer id){
    this.id = id;
    return this;
  }
  public  java.lang.String getNombre(){
    return this.nombre;
  }

  public  ProductoVO setNombre (java.lang.String nombre){
    this.nombre = nombre;
    return this;
  }
  public  java.lang.Long getPrecio(){
    return this.precio;
  }

  public  ProductoVO setPrecio (java.lang.Long precio){
    this.precio = precio;
    return this;
  }
  public  java.lang.Integer getStock(){
    return this.stock;
  }

  public  ProductoVO setStock (java.lang.Integer stock){
    this.stock = stock;
    return this;
  }
}