/*******************************************************************************
Code generated by platkmframework 
*******************************************************************************/
package org.platkmframework.example.openapi.controller;
import org.springframework.web.bind.annotation.*;


@RestController
@RequestMapping("/productos")
public class ApiController{

	  @PostMapping
	  public org.platkmframework.example.openapi.domain.vo.ProductoVO createProduct() {
        		return new org.platkmframework.example.openapi.domain.vo.ProductoVO() ;	
	  }

}

